// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pbf/orders/orders.proto

package orders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// PR is the price at which this order was placed in the orderbook.
	PR float32 `protobuf:"fixed32,1,opt,name=PR,proto3" json:"PR,omitempty"`
	// SI is the size at which this order was placed in the orderbook.
	SI float32 `protobuf:"fixed32,2,opt,name=SI,proto3" json:"SI,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_orders_orders_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_orders_orders_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pbf_orders_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetPR() float32 {
	if x != nil {
		return x.PR
	}
	return 0
}

func (x *Order) GetSI() float32 {
	if x != nil {
		return x.SI
	}
	return 0
}

type Bundle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AS is the list of asks for this bundle of orders.
	AK []*Order `protobuf:"bytes,1,rep,name=AK,proto3" json:"AK,omitempty"`
	// BD is the list of bids for this bundle of orders.
	BD []*Order `protobuf:"bytes,2,rep,name=BD,proto3" json:"BD,omitempty"`
	// TS is the timestamp at which this particular bundle was recorded.
	TS *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=TS,proto3" json:"TS,omitempty"`
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_orders_orders_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_orders_orders_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_pbf_orders_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Bundle) GetAK() []*Order {
	if x != nil {
		return x.AK
	}
	return nil
}

func (x *Bundle) GetBD() []*Order {
	if x != nil {
		return x.BD
	}
	return nil
}

func (x *Bundle) GetTS() *timestamppb.Timestamp {
	if x != nil {
		return x.TS
	}
	return nil
}

type Orders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// EX is the exchange identifier for this set of trades.
	EX string `protobuf:"bytes,1,opt,name=EX,proto3" json:"EX,omitempty"`
	// AS is the asset identifier for this set of trades.
	AS string `protobuf:"bytes,2,opt,name=AS,proto3" json:"AS,omitempty"`
	// ST is the start time for this set of trades.
	ST *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ST,proto3" json:"ST,omitempty"`
	// EN is the end time for this set of trades.
	EN *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=EN,proto3" json:"EN,omitempty"`
	// BU is the bundle of asks and bids for this set of orders.
	BU []*Bundle `protobuf:"bytes,5,rep,name=BU,proto3" json:"BU,omitempty"`
}

func (x *Orders) Reset() {
	*x = Orders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_orders_orders_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_orders_orders_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_pbf_orders_orders_proto_rawDescGZIP(), []int{2}
}

func (x *Orders) GetEX() string {
	if x != nil {
		return x.EX
	}
	return ""
}

func (x *Orders) GetAS() string {
	if x != nil {
		return x.AS
	}
	return ""
}

func (x *Orders) GetST() *timestamppb.Timestamp {
	if x != nil {
		return x.ST
	}
	return nil
}

func (x *Orders) GetEN() *timestamppb.Timestamp {
	if x != nil {
		return x.EN
	}
	return nil
}

func (x *Orders) GetBU() []*Bundle {
	if x != nil {
		return x.BU
	}
	return nil
}

var File_pbf_orders_orders_proto protoreflect.FileDescriptor

var file_pbf_orders_orders_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x62, 0x66, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x50,
	0x52, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x50, 0x52, 0x12, 0x0e, 0x0a, 0x02, 0x53,
	0x49, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x53, 0x49, 0x22, 0x72, 0x0a, 0x06, 0x42,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x41, 0x4b, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x02, 0x41, 0x4b, 0x12, 0x1d, 0x0a, 0x02, 0x42, 0x44, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x02, 0x42, 0x44, 0x12, 0x2a, 0x0a, 0x02, 0x54, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x54, 0x53, 0x22,
	0xa0, 0x01, 0x0a, 0x06, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x45, 0x58,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x45, 0x58, 0x12, 0x0e, 0x0a, 0x02, 0x41, 0x53,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x41, 0x53, 0x12, 0x2a, 0x0a, 0x02, 0x53, 0x54,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x53, 0x54, 0x12, 0x2a, 0x0a, 0x02, 0x45, 0x4e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02,
	0x45, 0x4e, 0x12, 0x1e, 0x0a, 0x02, 0x42, 0x55, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x02,
	0x42, 0x55, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbf_orders_orders_proto_rawDescOnce sync.Once
	file_pbf_orders_orders_proto_rawDescData = file_pbf_orders_orders_proto_rawDesc
)

func file_pbf_orders_orders_proto_rawDescGZIP() []byte {
	file_pbf_orders_orders_proto_rawDescOnce.Do(func() {
		file_pbf_orders_orders_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbf_orders_orders_proto_rawDescData)
	})
	return file_pbf_orders_orders_proto_rawDescData
}

var file_pbf_orders_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pbf_orders_orders_proto_goTypes = []interface{}{
	(*Order)(nil),                 // 0: orders.Order
	(*Bundle)(nil),                // 1: orders.Bundle
	(*Orders)(nil),                // 2: orders.Orders
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_pbf_orders_orders_proto_depIdxs = []int32{
	0, // 0: orders.Bundle.AK:type_name -> orders.Order
	0, // 1: orders.Bundle.BD:type_name -> orders.Order
	3, // 2: orders.Bundle.TS:type_name -> google.protobuf.Timestamp
	3, // 3: orders.Orders.ST:type_name -> google.protobuf.Timestamp
	3, // 4: orders.Orders.EN:type_name -> google.protobuf.Timestamp
	1, // 5: orders.Orders.BU:type_name -> orders.Bundle
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pbf_orders_orders_proto_init() }
func file_pbf_orders_orders_proto_init() {
	if File_pbf_orders_orders_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbf_orders_orders_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_orders_orders_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_orders_orders_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Orders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbf_orders_orders_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbf_orders_orders_proto_goTypes,
		DependencyIndexes: file_pbf_orders_orders_proto_depIdxs,
		MessageInfos:      file_pbf_orders_orders_proto_msgTypes,
	}.Build()
	File_pbf_orders_orders_proto = out.File
	file_pbf_orders_orders_proto_rawDesc = nil
	file_pbf_orders_orders_proto_goTypes = nil
	file_pbf_orders_orders_proto_depIdxs = nil
}
