// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pbf/trades/trades.proto

package trades

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// LI expresses whether this particular trade was caused by a liquidation.
	LI bool `protobuf:"varint,1,opt,name=LI,proto3" json:"LI,omitempty"`
	// PR is the price at which this trade was made.
	PR float32 `protobuf:"fixed32,2,opt,name=PR,proto3" json:"PR,omitempty"`
	// LO is the size of a long trade, if it was not a short trade.
	LO float32 `protobuf:"fixed32,3,opt,name=LO,proto3" json:"LO,omitempty"`
	// SH is the size of a short trade, if it was not a long trade.
	SH float32 `protobuf:"fixed32,4,opt,name=SH,proto3" json:"SH,omitempty"`
	// TS is the timestamp at which this particular trade happened.
	TS *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=TS,proto3" json:"TS,omitempty"`
}

func (x *Trade) Reset() {
	*x = Trade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_trades_trades_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_trades_trades_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_pbf_trades_trades_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetLI() bool {
	if x != nil {
		return x.LI
	}
	return false
}

func (x *Trade) GetPR() float32 {
	if x != nil {
		return x.PR
	}
	return 0
}

func (x *Trade) GetLO() float32 {
	if x != nil {
		return x.LO
	}
	return 0
}

func (x *Trade) GetSH() float32 {
	if x != nil {
		return x.SH
	}
	return 0
}

func (x *Trade) GetTS() *timestamppb.Timestamp {
	if x != nil {
		return x.TS
	}
	return nil
}

type Trades struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TR []*Trade `protobuf:"bytes,1,rep,name=TR,proto3" json:"TR,omitempty"`
}

func (x *Trades) Reset() {
	*x = Trades{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_trades_trades_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trades) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trades) ProtoMessage() {}

func (x *Trades) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_trades_trades_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trades.ProtoReflect.Descriptor instead.
func (*Trades) Descriptor() ([]byte, []int) {
	return file_pbf_trades_trades_proto_rawDescGZIP(), []int{1}
}

func (x *Trades) GetTR() []*Trade {
	if x != nil {
		return x.TR
	}
	return nil
}

var File_pbf_trades_trades_proto protoreflect.FileDescriptor

var file_pbf_trades_trades_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x62, 0x66, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x73, 0x2f, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x73, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4c,
	0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4c, 0x49, 0x12, 0x0e, 0x0a, 0x02, 0x50,
	0x52, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x50, 0x52, 0x12, 0x0e, 0x0a, 0x02, 0x4c,
	0x4f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x4c, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x53,
	0x48, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x53, 0x48, 0x12, 0x2a, 0x0a, 0x02, 0x54,
	0x53, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x02, 0x54, 0x53, 0x22, 0x27, 0x0a, 0x06, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x73, 0x12, 0x1d, 0x0a, 0x02, 0x54, 0x52, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x02, 0x54, 0x52,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x74, 0x72, 0x61, 0x64, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbf_trades_trades_proto_rawDescOnce sync.Once
	file_pbf_trades_trades_proto_rawDescData = file_pbf_trades_trades_proto_rawDesc
)

func file_pbf_trades_trades_proto_rawDescGZIP() []byte {
	file_pbf_trades_trades_proto_rawDescOnce.Do(func() {
		file_pbf_trades_trades_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbf_trades_trades_proto_rawDescData)
	})
	return file_pbf_trades_trades_proto_rawDescData
}

var file_pbf_trades_trades_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbf_trades_trades_proto_goTypes = []interface{}{
	(*Trade)(nil),                 // 0: trades.Trade
	(*Trades)(nil),                // 1: trades.Trades
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pbf_trades_trades_proto_depIdxs = []int32{
	2, // 0: trades.Trade.TS:type_name -> google.protobuf.Timestamp
	0, // 1: trades.Trades.TR:type_name -> trades.Trade
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbf_trades_trades_proto_init() }
func file_pbf_trades_trades_proto_init() {
	if File_pbf_trades_trades_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbf_trades_trades_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_trades_trades_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trades); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbf_trades_trades_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbf_trades_trades_proto_goTypes,
		DependencyIndexes: file_pbf_trades_trades_proto_depIdxs,
		MessageInfos:      file_pbf_trades_trades_proto_msgTypes,
	}.Build()
	File_pbf_trades_trades_proto = out.File
	file_pbf_trades_trades_proto_rawDesc = nil
	file_pbf_trades_trades_proto_goTypes = nil
	file_pbf_trades_trades_proto_depIdxs = nil
}
